frontend:
  - changed-files:
      - any-glob-to-any-file:
          - frontend/**
          - frontend/**/*

backend:
  - changed-files:
      - any-glob-to-any-file:
          - server/backend-api/**
          - server/backend-api/**/*

ml:
  - changed-files:
      - any-glob-to-any-file:
          - server/ml-service/**
          - server/ml-service/**/*

docs:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
